const colleges = {
  "bennett-university": {
    name: "Bennett University",
    shortName: "Bennett University",
    code: "BU",
    location: "Greater Noida",
    type: "Private",
    nirf: "Band 101-150",
    naac: "A+",
    rating: 4.5,
    coursesOffered: 28,
    examsAccepted: ["JEE Main", "CUET"],
    feesRange: "₹14 L - 22.5 L",
    fees: [{ total: "₹18.5L total" }],
    placements: { highest: "₹52 LPA", average: "₹9.1 LPA" },
    colors: { primary: "#2E2F31", accent: "#55565A" },
  },
  "galgotias-university": {
    name: "Galgotias University",
    shortName: "Galgotias University",
    code: "GU",
    location: "Greater Noida",
    type: "Private",
    nirf: "Band 151-200",
    naac: "A+",
    rating: 4.2,
    coursesOffered: 45,
    examsAccepted: ["JEE Main", "CUET"],
    feesRange: "₹10 L - 16 L",
    fees: [{ total: "₹14.2L total" }],
    placements: { highest: "₹41 LPA", average: "₹6.8 LPA" },
    colors: { primary: "#166534", accent: "#22C55E" },
  },
  "sharda-university": {
    name: "Sharda University",
    shortName: "Sharda University",
    code: "SU",
    location: "Greater Noida",
    type: "Private",
    nirf: "Band 151-200",
    naac: "A+",
    rating: 4.3,
    coursesOffered: 60,
    examsAccepted: ["NEET", "JEE Main"],
    feesRange: "₹11 L - 18 L",
    fees: [{ total: "₹15.8L total" }],
    placements: { highest: "₹38 LPA", average: "₹6.2 LPA" },
    colors: { primary: "#B91C4B", accent: "#EC4899" },
  },
  "amity-university-noida": {
    name: "Amity University, Noida",
    shortName: "Amity University",
    code: "AU",
    location: "Noida",
    type: "Private",
    nirf: "Band 101-150",
    naac: "A+",
    rating: 4.1,
    established: 2005,
    coursesOffered: 50,
    examsAccepted: ["CUET", "JEE Main"],
    feesRange: "₹12 L - 20 L",
    fees: [{ total: "₹16.9L total" }],
    placements: { highest: "₹45 LPA", average: "₹7.2 LPA" },
    colors: { primary: "#F9B929", accent: "#FFCF4D" },
  },
  "iimt-university": {
    name: "IIMT University, Meerut",
    shortName: "IIMT University",
    code: "IU",
    location: "Meerut",
    type: "Private",
    nirf: "Band 200+",
    naac: "A",
    rating: 3.9,
    established: 2016,
    coursesOffered: 20,
    examsAccepted: ["CUET"],
    feesRange: "₹6 L - 10 L",
    fees: [{ total: "₹8.4L total" }],
    placements: { highest: "₹12 LPA", average: "₹4.5 LPA" },
    colors: { primary: "#0F766E", accent: "#2DD4BF" },
  },
  "gd-goenka-university": {
    name: "GD Goenka University, Gurugram",
    shortName: "GD Goenka University",
    code: "GD",
    location: "Gurugram",
    type: "Private",
    nirf: "Band 151-200",
    naac: "A",
    rating: 4.0,
    established: 2013,
    coursesOffered: 15,
    examsAccepted: ["CUET"],
    feesRange: "₹9 L - 15 L",
    fees: [{ total: "₹12.6L total" }],
    placements: { highest: "₹22 LPA", average: "₹5.8 LPA" },
    colors: { primary: "#7C2D12", accent: "#EA580C" },
  },
  "chandigarh-university": {
    name: "Chandigarh University",
    shortName: "Chandigarh University",
    code: "CU",
    location: "Mohali",
    type: "Private",
    nirf: "Band 51-100",
    naac: "A+",
    rating: 4.4,
    established: 2012,
    coursesOffered: 60,
    examsAccepted: ["JEE Main", "CUET"],
    feesRange: "₹9 L - 14 L",
    fees: [{ total: "₹13.2L total" }],
    placements: { highest: "₹1.28 Cr", average: "₹6.1 LPA" },
    colors: { primary: "#1D4ED8", accent: "#60A5FA" },
  },
  "lovely-professional-university": {
    name: "Lovely Professional University",
    shortName: "LPU",
    code: "LPU",
    location: "Phagwara, Punjab",
    type: "Private",
    nirf: "Band 51-100",
    naac: "A++",
    rating: 4.3,
    established: 2005,
    coursesOffered: 60,
    examsAccepted: ["LPUNEST", "CUET"],
    feesRange: "₹8 L - 13 L",
    fees: [{ total: "₹11.8L total" }],
    placements: { highest: "₹1.1 Cr", average: "₹5.4 LPA" },
    colors: { primary: "#9333EA", accent: "#C084FC" },
  },
};

export default colleges;